Revert "fix: Use always()"
This reverts commit df082206b04eb8802544c03e696bdff74ba46d2d.

diff --git a/.github/workflows/unit-test.yml b/.github/workflows/unit-test.yml
--- a/.github/workflows/unit-test.yml
+++ b/.github/workflows/unit-test.yml
@@ -14,7 +14,6 @@ jobs:
       - uses: actions/checkout@v3
       - name: Cache poetry installation
         id: cache-poetry
-        if: ${{ always() }}
         uses: actions/cache@v3
         with:
           path: ${{ github.workspace }}/pipx/venvs/poetry/**
@@ -23,25 +22,25 @@ jobs:
         if: ${{ steps.cache-poetry.outputs.cache-hit != 'true' }}
         run: PIPX_HOME=$GITHUB_WORKSPACE/pipx pipx install poetry
       - run: echo "$GITHUB_WORKSPACE/pipx/venvs/poetry/bin" >> $GITHUB_PATH
-      - if: ${{ always() }}
-        uses: actions/setup-python@v4
+      - uses: actions/setup-python@v4
         with:
           python-version: '3.8' 
           cache: 'poetry'
       - run: poetry install
-      - run: PYTHONPATH=src poetry run pytest tests/ --cov=src --cov-report html:cov_html > unit-test-output.txt
+      - id: pytest
+        run: PYTHONPATH=src poetry run pytest tests/ --cov=src --cov-report html:cov_html > unit-test-output.txt
+        continue-on-error: true
       - name: Upload coverage report
-        if: ${{ always() }}
         uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
         with:
           name: coverage-${{ github.run_id }}
           path: ${{ github.workspace }}/cov_html/
       - name: Display test report
-        if: ${{ always() }}
         run: cat unit-test-output.txt
       - name: Upload test report
-        if: ${{ always() }}
         uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
         with:
           name: unit-test-output-${{ github.run_id }}
           path: ${{ github.workspace }}/unit-test-output.txt
+      - if: ${{ steps.pytest.outcome == 'failure' }}
+        run: echo "Unit test failed!" && exit 1
